### ISSUE TITLE
Masculine first declension nouns ending in -ας

### ISSUE THREAD

**Issue by AndreiChura** [neelsmith/Kanones.jl#324]
Create a regular first declension noun class for the masculine nouns ending in -ας.

**Comment by neelsmith** [comment]
Not sure what pattern you want -- can you give an example noun?

**Comment by AndreiChura** [comment]
Examples would be: Πελίας -ου, Τειρεσίας -ου, and Αὐγείας -ου. They have the same endings in every other form as the masculine first declension nouns with nominative singular forms ending in -ης.

**Comment by neelsmith** [comment]
done
