### ISSUE TITLE
Third declension noun class ending in -ηρ -ερος

### ISSUE THREAD

**Issue by AndreiChura** [neelsmith/Kanones.jl#341]
Create a third declension regular noun class for nouns ending in -ηρ -ερος. Ex: θυγάτηρ, θυγατέρος; μήτηρ, μητέρος.

**Comment by neelsmith** [comment]
Both of these examples parse using the data in the current core parser.  μήτηρ is an irregular noun;  θυγάτηρ belongs to the stem class `0_os`.

Closing as resolved
